### PR TITLE
Upgrade to ruTorrent v4.2.9

### PR DESCRIPTION
**Pull request by stickz**
**v4.2.7**
- Correct Turkish translations 
- Fix image error in web console with DarkBetter theme 
- Fix PHP 8.2 deprecation warnings 
- Fix JS error updating null labels 
- Fix oblivion theme text on torrent creation
- Fix port checker api

**v4.2.8**
* Fix element jquery type confusion
* scroll-table: Fix unhandled undefined attr
* trafic: Fix resize when plot undefined

**v4.2.9**
- Fixed JavaScript errors associated with adding and removing search tags.
- Fixed the seedingtime plugin not updating finished time without a page refresh
- Fixed the file list disappearing occasionally when using the double click download feature.

### CODE REVIEW

**Comment by ac1dburnz** [comment]
@stickz  should we change this to 4.2.8?

**Comment by stickz** [comment]
> @stickz should we change this to 4.2.8?

Yes we shall.

**Comment by stickz** [comment]
@crazy-max We should be done releasing new ruTorrent versions for a while now. There are 10 different fixes here, some critical.

**Review by crazy-max — APPROVED** [review]
LGTM sorry for the delay

**Pull request merged**
