### PR TITLE
Add custom download path support

### PR DESCRIPTION
**Pull request by guardmedia**

### CODE REVIEW

**Comment by zimmertr** [comment]
In the interim you can just mount in a custom rtlocal.rc file and specify it there.

https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps/blob/a88778f693f1d914c817101b3dc384ba34da6d9b/ruTorrent/overlays/example/rutorrent/rtlocal.rc#L4

**Comment by netty0** [comment]
> In the interim you can just mount in a custom rtlocal.rc file and specify it there.
> 
> https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps/blob/master/ruTorrent/overlays/example/rutorrent/rtlocal.rc#L4

Would you have an example of how you mounted a custom rtlocal.rc to override the default? Thank you

**Comment by zimmertr** [comment]
In hindsight I think I lied to you. IIRC when the container initializes without an existing data directory it will copy the generated `rtlocal.rc` into place. So even if you pass one on your first boot it will get overwritten. 

I run this with Kubernetes so I cannot give you a Docker-pure example. But if you take a couple steps up in the link I shared you can see my [Kustomize manifests](https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps/tree/master/ruTorrent). 

My strategy was to start the container and let ruTorrent initialize the configuration directory that is volume mounted outside of the container. Then shut it down and move `rtlocal.rc` into place at `rtorrent/data/`. Then restart the container to apply the configuration file.

[Here](https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps/blob/master/ruTorrent/overlays/example/rutorrent/dep.yml#L48) are the volume mounts for my Kubernetes Deployment. You should be able to replicate them with `-v` arguments with Docker pure.

**Comment by neo-neo1** [comment]
@crazy-max are you still maintaining this project? Been several months for commits to be reviewed. Thanks for your work

**Comment by Anthirian** [comment]
> In hindsight I think I lied to you. IIRC when the container initializes without an existing data directory it will copy the generated `rtlocal.rc` into place. So even if you pass one on your first boot it will get overwritten.

I learned this the hard way today as well. I ended up cloning the repository and editing the `rootfs/tpls/etc/rtorrent/.rtlocal.rc` file there, then rebuilding the image and tagging it with a custom label and finally using that in my `docker-compose.yml`. 

The Kubernetes version you describe seems to be just as much work, so a big 👍🏻 from me on the proposed solution 😄

**Comment by neo-neo1** [comment]
> @crazy-max any chance of merging this? It's an extremely helpful change that none of the popular images have.

Seems this has been abandoned. No word from the creator in a long time. There’s another PR that was also left without a reply.

**Comment by doob187** [comment]
Simple build on top 

And don't wait until it will Merged 

docker-rutorrent/root/04overwrite.sh

```sh
Dockerfile 

ARG VERSION
FROM ghcr.io/crazy-max/rtorrent-rutorrent:${VERSION}

COPY ./apps/docker-rutorrent/root/04-overwrite.sh /etc/cont-init.d/04-overwrite.sh

RUN chmod a+x /etc/cont-init.d/04-overwrite.sh && mv /etc/cont-init.d/04-create-services.sh /etc/cont-init.d/05-create-services.sh

ENTRYPOINT [ "/init" ]

HEALTHCHECK --interval=30s --timeout=20s --start-period=10s \
CMD /usr/local/bin/healthcheck
```


```sh
#!/usr/bin/with-contenv sh
RU_DOWNLOAD_FOLDER=${RU_DOWNLOAD_FOLDER:-/downloads}
# Custom Folder
if [[ "${RU_DOWNLOAD_FOLDER}" != "/downloads" ]]; then
   rm -rf /downloads/{complete,temp}
   mkdir -p ${RU_DOWNLOAD_FOLDER} \
    ${RU_DOWNLOAD_FOLDER}/complete \
    ${RU_DOWNLOAD_FOLDER}/temp

   echo "  Enabling Custom Download Folder for rTorrent..."
   sed -i "s#/downloads#${RU_DOWNLOAD_FOLDER}#g" /etc/rtorrent/.rtlocal.rc
   echo "... Fixing perms for Custom Folders ..."
   chown rtorrent. \
    ${RU_DOWNLOAD_FOLDER} \
    ${RU_DOWNLOAD_FOLDER}/complete \
    ${RU_DOWNLOAD_FOLDER}/temp
fi

#E-o-F
```

**Comment by hollanbm** [comment]
I forked and merged this PR, and uploaded the resultant image to my dockerhub repo [mrbucket101/rtorrent-rutorrent](https://hub.docker.com/repository/docker/mrbucket101/rtorrent-rutorrent)

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/105#issuecomment-1112681278

**Comment by thiccglobs** [comment]
> Simple build on top

Good answer, script worked for me.  Thanks! :+1:

**Pull request closed without merging**
