### PR TITLE
Update rutorrent to 4.2.2

### PR DESCRIPTION
**Pull request by ac1dburnz**
### Update to v4.2.2-stable

**ruTorrent Development Note**

We are pleased to announce ruTorrent v4.2 will now be marked as stable. This is anther major milestone in ruTorrent development. We will be supporting ruTorrent v4.1 for a while longer. It's not required to upgrade yet, unless you want the latest bleeding edge improvements.

**What's Changed**

Improve performance of webui and sort table by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2469
Material design fixes by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2522
Scroll table fixes by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2524
webui: Add quick search by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2525
style: Darken cover for dark themes by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2523
webui: Avoid unnecessary label text update by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2533
index: Cleanup html and translations by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2534
webui: Add Views panel by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2535
style: Add button hover indication by @TrimmingFool in https://github.com/Novik/ruTorrent/pull/2538
Fix status bar overflow & min width on mobile by @stickz in https://github.com/Novik/ruTorrent/commit/420606059e2ab1a81242f9e93e310a63ac99bb7b
Upgrade to jQuery 3.7 by @stickz in https://github.com/Novik/ruTorrent/commit/048f792eec4314010c329684cc62986d2177763e
Fix UTF8 encoding bug with labels by @stickz in https://github.com/Novik/ruTorrent/commit/cdec4814b31cb388fb7c5718775ed4dada208c69

**Performance Improvements**

Greatly improved WebUI performance using asynchronous background task for torrent information updates. Thanks @TrimmingFool.
Upgraded jQuery from v3.6 to v3.7 to improve performance of appending objects to the DOM by @stickz.

**New Features**

Added a new WebUI views feature where different labels or torrents can now be grouped together to form a single "view". This increases the flexibly of ruTorrent to display customized groups of torrents, without having to rework labels. Thanks @TrimmingFool.
Improved quick search implementation. Press keydown to search immediately or enter to add the search tag by @TrimmingFool.
Added dark loading screen feature for dark themes by @TrimmingFool.

**Bug Fixes**

Resolved status bar overflow on mobile devices by hiding and condensing information as the screen width shrinks by @stickz.
Added min width to category list to prevent resizing to value where text flows off the screen by @stickz.
Hide the search bar when the screen width is too small, to prevent menu items from breaking by @stickz.
Fixed a UTF8 encoding bug with the autotools plugin by @stickz.
Cleaned up some deprecated features in the index.html by @TrimmingFool.
Fixed multiple bugs and display issues with the Material Design theme by @TrimmingFool.

### CODE REVIEW

**Comment by stickz** [comment]
@crazy-max We have a critical hot fix coming for `ruTorrent v4.2`. It's probably best to wait for it. There are regressions here.

**Comment by ac1dburnz** [comment]
thanks @stickz  I updated it.

**Review by stickz — APPROVED** [review]

**Comment by stickz** [comment]
@ac1dburnz @crazy-max version 4.2.2 being released tomorrow. There is a known issue with the `autotools` plugin.

**Comment by ac1dburnz** [comment]
lol updated it again

**Comment by crazy-max** [comment]
@ac1dburnz Can you squash your commits please? Thanks.

**Pull request closed without merging**
