### PR TITLE
ruTorrent v4.0.2-hotfix

### PR DESCRIPTION
**Pull request by stickz**
Bumps ruTorrent version to 4.0.2-hotfix for additional stability improvements.
https://github.com/Novik/ruTorrent/releases/tag/v4.0.2

`$cachedPluginLoading` should be set to `false`. It is not stable yet.

### CODE REVIEW

**Review by crazy-max — APPROVED** [review]
LGTM thanks!

**Comment by albarracin-adn** [comment]
Good evening, I just installed the docker image and after installing it, when I start the rutorrent I get two warnings, in which I attach a screenshot. how can it be solved?

https://i.imgur.com/uX62wbk.png

the machine is an Odroid-C2 and the OS is armbian

thank you.

**Comment by stickz** [comment]
@albarracin-adn Could you please attach the image directly to GitHub? The website is not working for me.

**Comment by stickz** [comment]
@albarracin-adn Please clear your web browser cache. A possible cause for this type of error is caching issues.

**Comment by albarracin-adn** [comment]
> @albarracin-adn Could you please attach the image directly to GitHub? The website is not working for me.
> 
> Edit: See attached image bellow. I changed my ip address to bypass website restrictions. uX62wbk

Screenshot_41

the browser i use is google chrome

**Comment by albarracin-adn** [comment]
> @albarracin-adn Please clear your web browser cache. A possible cause for this type of error is caching issues.

Thank you very much, that was it. It is assumed that I am a computer scientist and I have not fallen into the cache, previously I used another image and it must have been for that reason. Really thanks.

**Pull request merged**
