### PR TITLE
ruTorrent v4.2.5

### PR DESCRIPTION
**Pull request by ac1dburnz**
Updated to 4.2.4 
This hotfix resolves a critical regression with ruTorrent v4.2.3 when adding a new torrent. It's crucial to upgrade.

### CODE REVIEW

**Comment by djerfy** [comment]
> Updated to 4.2.4 This hotfix resolves a critical regression with ruTorrent v4.2.3 when adding a new torrent. It's crucial to upgrade.

Thanks a lot. A crucial update from version 4.2.3 ([all changelog 4.2.2...4.2.4](https://github.com/Novik/ruTorrent/compare/v4.2.2...v4.2.4))

**Review by stickz — APPROVED** [review]

**Comment by stickz** [comment]
`ruTorrent v4.2.5` is the most stable release. It's safe to merge this commit.

Perhaps change title to "Upgrade to ruTorrent v4.2.5 and squash your commits.

**Review by crazy-max — CHANGES_REQUESTED** [review]
Thanks but please squash commits and make relevant commit message: https://github.com/crazy-max/docker-rtorrent-rutorrent/commit/d30aa11894fdcd484754935e6d74fd3fe42d2901

`ruTorrent v4.2.5`

Edit: @stickz You beat me to it :sweat_smile:

**Comment by ac1dburnz** [comment]
I think i did it right. Sorry, I had these changes locally and didn't push it. I Think it's done right now though.

**Comment by ac1dburnz** [comment]
Ah gotcha. Did it:) thanks for that @V33m !

**Review by crazy-max — APPROVED** [review]
Updated commit message myself

**Pull request merged**
