### PR TITLE
Upgrade to rTorrent v5.5

### PR DESCRIPTION
**Pull request by stickz**
**Full Changelog**: https://github.com/stickz/rtorrent/compare/v5.3-0.9.8-0.13.8...v5.5-0.9.8-0.13.8

## What's Changed
* https://github.com/stickz/rtorrent/pull/28
* https://github.com/stickz/rtorrent/pull/29
* https://github.com/stickz/rtorrent/pull/32
* https://github.com/stickz/rtorrent/pull/33
* https://github.com/stickz/rtorrent/pull/35
* https://github.com/stickz/rtorrent/pull/36

### CODE REVIEW

**Comment by stickz** [comment]
@crazy-max UDNS is currently disabled by default. It was tested with hundreds of instances. The crash volume was too high compared to synchronous DNS resolution. Once the unreported crash is resolved, we plan to re-enable the future. We have a stack trace for the crash. Working on getting a more detailed one, as it can't be restimulated in every environment.

Two hash threads instead of one is currently working stable. When multiple downloads are active, the 30% load is successfully split between two threads of 15% each. Half the downloads are assigned to each thread. This is more scalable for multiple instances. Event signals are sent to each hash thread to active them. They basically sleep when not being used to avoid incurring overhead.

rTorrent v5.5 is the final and most stable release for version 5. I'm working on getting all platforms upgraded before the version 6 stability release. We need to ensure all bug reports are on the latest version, to avoid stale information from circulating.

**Comment by crazy-max** [comment]
Looking at UDNS handling in libtorrent I was wondering if we could have an interface to use a third-party resolver. We could then defer to a sidecar container exposing a dns forwarder such as https://github.com/crazy-max/docker-unbound

**Comment by stickz** [comment]
> Looking at UDNS handling in libtorrent I was wondering if we could have an interface to use a third-party resolver. We could then defer to a sidecar container exposing a dns forwarder such as https://github.com/crazy-max/docker-unbound

Yes, we can add a configure option like `--enable-resolver` with an `AC_DEFINE` and `LIBS` addition to only include third-party resolver in the build when enabled. https://github.com/stickz/rtorrent/blob/master/libtorrent/scripts/udns.m4

**Comment by stickz** [comment]
Closing this off in favour of upgrading to version 6! The stability issues with UDNS are now fixed and performance is improved!

**Pull request closed without merging**
